org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.experimental.enableScreenshotTest=true
android.compose.screenshot.maxHeapSize=4g

GROUP=io.github.mamby.androidkit
VERSION_NAME=0.1.0-SNAPSHOT
POM_URL=https://github.com/mamby/android-kit
POM_SCM_URL=https://github.com/mamby/android-kit
POM_SCM_CONNECTION=scm:git:https://github.com/mamby/android-kit.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/mamby/android-kit.git
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_DEVELOPER_ID=mamby
POM_DEVELOPER_NAME=Mamby Camara
